# Generated by Django 6.0.3 on 2026-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='github_repo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='github_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
