# Generated by Django 6.0.3 on 2026-05-22 18:44

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='github_token',
            field=core.models.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
